NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transfrom, and matrices.
NumPy was created in 2005 by Travis Oliphant
It is an open source project and you can use it freely
NumPy stands for Numerical Python.

WHY USE NUMPY
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in a data science, where speed and resources are very important.

WHY IS NUMPY FASTER THAN LISTS?

NumPy arrays are stored at one continuoes place in memory unlike lists, so processes can access and amnipulate them very efficiently.
This behavuoir is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists.
aslo it is optimized to work with latest CPU architectures.

WHICH LANGUAGE IS NUMPY WRITTEN IN?
NumPy is a Python library and is written partially in python, but most of the parts that require fast computation are written in C or C++

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


NumPy is usually imported under the np alias

alias : in Python alias are an alternate name for referring to the smae thing

Create an alias with the as keyword while importing

Improt numpy as np

Now the NumPy package can be referrend to as np instead of numpy

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
#CHECKING NUMPY VERSION
#The version string is stored under __version__ attribute

import numpy as np
print(np.__version__)

2.5.0


Creating Arrays
Create a NumPy ndarray Object

NumPy is used to work with arrays.
The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function



In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): 
This built-in Python function tells us the type of the object passed to it. 
Like in above code it showsn that arr is numpy.ndarray type.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
#Use a tuple to create a NumPy array:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


DIMENSIONS IN ARRAYS

A dimension in arrays is one level of array depth (nested arrays).

nested array:
are arrays that have arrays as their elements

0-D Arrays

0-D arrays, or Scalars, are the elements in an array.
Each value in an array is a 0-D array

In [6]:
#Create a 0-D array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.


In [7]:
#Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat


In [8]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.



In [9]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integere that tells us how many dimensions the array have.

In [10]:
#Check how many dimensions the arrays have:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,2],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


HIGHER DIMENSIONAL ARRAYS

An array can have any number of dimensions

When the array is created, you can define the number of dimensions by using the ndmin argument


In [11]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In this array the innermost dimension(5th dim) has 4 elements, 
the 4th dim has 1 element that is the vector,
the 3rd dim has 1 element that is the matrix with the vector,
the 2nd dim has 1 element that is 3D array and 1st element that is a 4D array.

ARRAY INDEXING

Access Array Elements

Array indexing is the same as accessing an array element

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.


In [1]:
#Get the first element from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [2]:
#Get the second element from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [ ]:
#Get the third and fourth element from the following array and add them:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


ACCESS 2-D ARRAYS
To access elements from 2-D arrays we can use comma separated integers representating the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column

In [4]:
#Access the element on the first row, second column:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [1]:
#Access the element on the 2nd row, 5th column:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ',arr[1,4])

5th element on 2nd row:  10


ACCESS 3-D ARRAYS

To access elements from 3-d arrays we can use somma separated integers representating the dimesions and the index of the element.


In [1]:
#Access the third element of the second array of the forst array:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


EX EXPLAINED

arr[0,1,2] prints the value 6

The first number represents the first dimension, which contains two arrays: [[1,2,3][4,5,6]] and [[7,8,9],[10,11,12,]]
since we selected 0, we are left with the first array: [[1,2,3],[4,5,6]]

The second number represents the second dimension, which also contains two arrays: [1,2,3] and [4,5,6]
Since we selected 1 we are left with the second array: [4,5,6]

the third number represents th ethird dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6 

NEGATIVE INDEXING

Use negative indexing to access an array from the end

In [2]:
#Print the last element from the 2nd dim:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ',arr[1, -1])

Last element from 2nd dim:  10


ARRAY SLICING

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this : [start:end]
We can also define the setp, like this : [start:end:step]
If we don't pass start its considerd 0
if we don't pass end its considerd length of array in that dimension
if we don't pass step its considerd 1


In [3]:
#Slice elements from index 1 ro index 5 from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


Note: The result includes the start index, but excludes the end index

In [4]:
#Slice elements from index 4 to the end of the array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [5]:
#slice elements from the beginning to index 4 (not included)
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


NEGATIVE SLICING

Use the minus operator to refer to an index from the end:

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


STEP

Use the step value to determine the step of the slicing:

In [3]:
#Return every other element from index 1 to index 5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [4]:
#Return every other element from the entire array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [1]:
#SLICING 2-D ARRAYS
#From the second element, slice elements from index 1 to index 4 (not included):
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


Note: Remember that second element has index 1


In [2]:
#From both elements, return index 2:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [1]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


NUMPY DATA TYPES

DATA TYPES IN PYTHON

By default python have these data types:
- strings   : used to represent text data, the text is given under quore marks --- "ABCD"
- integer   : used to represent integer numbers -- -1, -2, -3
- float     : used to represent real number  --- 1.2, 42,42
- boolean   : used to represent True or False
- complex   ; used to represent complex number  --- 1.0_2.0j, 1.5+2.5j


DATA TYPESN IN NUMPY
NUMPY HAS SOME EXTRA DATA TYPES, AND REFER TO DATA TYPES WITH ONE CHARACTER, like i for integeres, u for unsigned integers.

Below a list of all data types in NumPy and the characters used to represent them.

i -integer
b - boolean
u - unsigned integre
f - floar
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type(void)