NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transfrom, and matrices.
NumPy was created in 2005 by Travis Oliphant
It is an open source project and you can use it freely
NumPy stands for Numerical Python.

WHY USE NUMPY
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in a data science, where speed and resources are very important.

WHY IS NUMPY FASTER THAN LISTS?

NumPy arrays are stored at one continuoes place in memory unlike lists, so processes can access and amnipulate them very efficiently.
This behavuoir is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists.
aslo it is optimized to work with latest CPU architectures.

WHICH LANGUAGE IS NUMPY WRITTEN IN?
NumPy is a Python library and is written partially in python, but most of the parts that require fast computation are written in C or C++

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


NumPy is usually imported under the np alias

alias : in Python alias are an alternate name for referring to the smae thing

Create an alias with the as keyword while importing

Improt numpy as np

Now the NumPy package can be referrend to as np instead of numpy

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
#CHECKING NUMPY VERSION
#The version string is stored under __version__ attribute

import numpy as np
print(np.__version__)

2.5.0


Creating Arrays
Create a NumPy ndarray Object

NumPy is used to work with arrays.
The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function



In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): 
This built-in Python function tells us the type of the object passed to it. 
Like in above code it showsn that arr is numpy.ndarray type.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
#Use a tuple to create a NumPy array:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


DIMENSIONS IN ARRAYS

A dimension in arrays is one level of array depth (nested arrays).

nested array:
are arrays that have arrays as their elements

0-D Arrays

0-D arrays, or Scalars, are the elements in an array.
Each value in an array is a 0-D array

In [6]:
#Create a 0-D array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.


In [7]:
#Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat


In [8]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.



In [9]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integere that tells us how many dimensions the array have.

In [10]:
#Check how many dimensions the arrays have:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,2],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


HIGHER DIMENSIONAL ARRAYS

An array can have any number of dimensions

When the array is created, you can define the number of dimensions by using the ndmin argument


In [11]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In this array the innermost dimension(5th dim) has 4 elements, 
the 4th dim has 1 element that is the vector,
the 3rd dim has 1 element that is the matrix with the vector,
the 2nd dim has 1 element that is 3D array and 1st element that is a 4D array.